### ISSUE TITLE
Support for adaptive icon

### ISSUE THREAD

**Issue by lokesh-krishna** [TobiPristupin/RUN#2]
Could you please consider adding support for adaptive icons?

If you could share the vector source for the current icon, I would like to make PR.

**Comment by TobiPristupin** [comment]
Absolutely! I would really appreciate a PR. 

I used [this](https://android-material-icon-generator.bitdroid.de/)  website to create the icon, with the "select material icon" option to create it, which gives you pngs for each dpi and one svg. Is the svg file the one you need? I'm clueless with design. I'll attach it just in case.

I've been playing with the idea of making the background white and the icon red, so I'll send that svg also. If you make a pr I'll let you choose which one to use :)

If the svgs aren't useful, the icon is dead simple, so you can easily recreate it. It's a circular background with the material icon "timeline" on it, the red is #b71c1c and the white is #ffffff.

[svgicons.zip](https://github.com/TobiPristupin/RUN/files/2043223/svgicons.zip)

**Comment by lokesh-krishna** [comment]
Closing this because #3 has been merged.
